# Generated by Django 4.2.5 on 2023-09-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=35, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='oficina',
            field=models.CharField(max_length=7, verbose_name='Oficina N°'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='piso',
            field=models.PositiveSmallIntegerField(verbose_name='Piso'),
        ),
    ]
