# Generated by Django 4.2.5 on 2023-09-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_empleado_habilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='Habilidades',
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
    ]
