# Generated by Django 4.2.5 on 2023-09-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='ValorPredeterminado', max_length=30, verbose_name='Nombre')),
                ('sigla', models.CharField(default='ValorPredeterminado', max_length=10, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'sigla')},
            },
        ),
    ]
