# Generated by Django 4.2.5 on 2023-09-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='sigla',
            field=models.CharField(max_length=10, verbose_name='Sigla'),
        ),
    ]
