# Generated by Django 4.2.5 on 2023-10-07 15:36

import aplicaciones.descuentos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrito', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venc', models.DateField(verbose_name='Fecha de vencimiento')),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venc', models.DateField(verbose_name='Fecha de vencimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id_descuentos', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del descuento')),
                ('porcentaje', models.IntegerField(blank=True, null=True, validators=[aplicaciones.descuentos.models.validate_two_digit], verbose_name='Porcentaje de descuento')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Valor de descuento')),
                ('carritos', models.ManyToManyField(through='descuentos.DescuentoCarrito', to='carrito.carrito')),
                ('productos', models.ManyToManyField(through='descuentos.DescuentoProducto', to='producto.producto')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DescuentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venc', models.DateField(verbose_name='Fecha de vencimiento')),
                ('id_descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descuentos.descuentos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='descuentos',
            name='usuarios',
            field=models.ManyToManyField(through='descuentos.DescuentoUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='descuentoproducto',
            name='id_descuento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descuentos.descuentos'),
        ),
        migrations.AddField(
            model_name='descuentoproducto',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
        migrations.AddField(
            model_name='descuentocarrito',
            name='id_descuento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descuentos.descuentos'),
        ),
    ]
