# Generated by Django 4.2.5 on 2023-10-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0002_producto_imagen'),
        ('pedido', '0001_initial'),
        ('descuentos', '0001_initial'),
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('id_finanzas', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_reporte', models.CharField(choices=[('0', 'Capital'), ('1', 'Ganancias'), ('2', 'Gastos')], max_length=1, verbose_name='Tipo de reporte')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('Departamentos', models.ManyToManyField(blank=True, to='departamento.departamento')),
                ('Descuentos', models.ManyToManyField(blank=True, to='descuentos.descuentos')),
                ('Pedidos', models.ManyToManyField(blank=True, to='pedido.pedido')),
                ('Productos', models.ManyToManyField(blank=True, to='producto.producto')),
            ],
            options={
                'verbose_name': 'Finanzas',
                'verbose_name_plural': 'Reportes de Finanzas',
                'ordering': ['fecha'],
            },
        ),
    ]
