# Generated by Django 4.2.5 on 2023-09-16 00:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_alter_categoria_nombre_alter_categoria_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Medida')),
                ('tipo_medida', models.CharField(choices=[('0', 'Grs'), ('1', 'Kgs'), ('2', 'Cm3'), ('3', 'Mls'), ('4', 'Lts')], max_length=1, verbose_name='Tipo de medida')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'id', 'tipo_medida', 'medida')},
            },
        ),
    ]
