# Generated by Django 4.2.5 on 2023-10-06 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('medida', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Medida')),
                ('tipo_medida', models.CharField(choices=[('0', 'Grs'), ('1', 'Kgs'), ('2', 'Cm3'), ('3', 'Mls'), ('4', 'Lts')], max_length=1, verbose_name='Tipo de medida')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio ($)')),
                ('categoria', models.ManyToManyField(to='categoria.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'codigo', 'tipo_medida', 'medida')},
            },
        ),
    ]
